# Generated by Django 3.2.4 on 2021-06-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_info',
            field=models.JSONField(default=dict),
        ),
    ]
